kernel: kernel-thermonuclear kernel-neutrino kernel-hydro
	@
	
kernel-rocm: kernel-rocm-thermonuclear kernel-rocm-neutrino kernel-rocm-hydro
	@

include src/kernel/neutrino/Makefile
include src/kernel/hydro/Makefile
include src/kernel/thermonuclear/Makefile
