kernel: kernel-thermonuclear kernel-neutrino kernel-hydro kernel-advout
	@
	
kernel-rocm: kernel-rocm-thermonuclear kernel-rocm-neutrino kernel-rocm-hydro kernel-advout
	@

include src/kernel/neutrino/Makefile
include src/kernel/hydro/Makefile
include src/kernel/thermonuclear/Makefile
include src/kernel/advout/Makefile
