test: apollo
	$(TIME_CMD) \
	$(APOLLO_RUN_CMD)
	
test-mem: apollo
	valgrind --leak-check=full $(APOLLO_RUN_CMD)

PROFILEFLAGS = CPUPROFILE=/tmp/prof.out
test-prof: apollo
	rm $(BUILD_DIR)/apollo
	$(HIPCC) $(BUILD_DIR)/src/*.o -o $(BUILD_DIR)/apollo $(CLIBS) -lprofiler
	
	$(PROFILEFLAGS) $(APOLLO_RUN_CMD)
	
	pprof ./build/apollo /tmp/prof.out

test-gdb: apollo
	gdb --args $(APOLLO_RUN_CMD)
	
test-rocm: apollo-rocm
	$(TIME_CMD) \
	$(APOLLO_ROCM_RUN_CMD)
