test: apollo
	$(TIME_CMD) \
	$(APOLLO_RUN_CMD)
	
test-mem: apollo
	@echo "Valgrind WILL BREAK YOUR SYSTEM"
	@echo "A new mem check solution is being worked on!"
	# valgrind $(APOLLO_RUN_CMD)

PROFILEFLAGS = CPUPROFILE=/tmp/prof.out
test-prof: apollo
	rm $(BUILD_DIR)/apollo
	$(HIPCC) $(BUILD_DIR)/src/*.o -o $(BUILD_DIR)/apollo $(CLIBS) -lprofiler
	
	$(PROFILEFLAGS) $(APOLLO_RUN_CMD)
	
	pprof ./build/apollo /tmp/prof.out

test-gdb: apollo
	gdb --args $(APOLLO_RUN_CMD)
