[simulation]

[simulation.time]
endtime = 1.0 # in seconds
tres = 100 # Temporal resolution of output
printkerneltime = true
initdt = 1e-1

[simulation.output]
output = true
outputdir = "output"

# No AMR
[simulation.resolution]
x = 4
y = 4
z = 1
# Setting this to 1 means 2D, and is much friendlier with visualization.

[simulation.hydro]
use = true
outputfile = "hydro.out"
effect = true

# Use of hydroeffect is required at the moment since we cannot import data.
[simulation.hydroeffect]

[simulation.hydroeffect.temp]
base = 8e09
effect = "radial"

[simulation.hydroeffect.density]
base = 1e08
effect = "radial"

# NOTE: these relative paths are relative to Makefile.test
[simulation.thermo]
use = true
networkfile = "data/network-alpha.aad"
ratefile = "data/ratelibrary-alpha.aad"

[simulation.neutrino]
use = true
opacityfile = "data/FENNData40M186.h5"

# For the python code only.
[visualization]
save = false
saveas = "out.mp4"
