[simulation]

[simulation.time]
endtime = 100.0 # in seconds
# For now dt is in the driver.

[simulation.output]
output = true
outputdir = "output"
tres = 100 # Temporal resolution of output

# No AMR
[simulation.resolution]
x = 64
y = 64
z = 1
# Setting this to 1 means 2D, and is much friendlier with visualization.

[simulation.hydro]
use = true
outputfile = "hydro.out"
effect = true

[simulation.hydroeffect]

[simulation.hydroeffect.temp]
effect = "radial"

[simulation.hydroeffect.density]
effect = "radial"

[simulation.thermo]
use = false
# inputfile = "foobar"

[simulation.neutrino]
use = false
# inputfile = "foobar"

# For the python code only.
[visualization]
save = true
saveas = "out.mp4"
