[simulation]

[simulation.time]
endtime = 400.0 # in seconds
# For now dt is in the driver.

[simulation.output]
output = true
outputdir = "output"
tres = 100 # Temporal resolution of output

# No AMR
[simulation.resolution]
x = 256
y = 256
z = 1
# Setting this to 1 means 2D, and is much friendlier with visualization.

[simulation.hydro]
use = true
outputfile = "hydro.out"
effect = true

# Use of hydroeffect is required at the moment since we cannot import data.
[simulation.hydroeffect]

[simulation.hydroeffect.temp]
base = 8e09
effect = "radial"

[simulation.hydroeffect.density]
base = 1e08
effect = "radial"

[simulation.thermo]
use = false
# inputfile = "foobar"

[simulation.neutrino]
use = false
# inputfile = "foobar"

# For the python code only.
[visualization]
save = false
saveas = "out.mp4"
