[simulation]

[simulation.time]
endtime = 1e6
tres = 100
printkerneltime = false
initdt = 1e2

[simulation.output]
output = true
outputdir = "output"

[simulation.resolution]
x = 128
y = 1
z = 1

[simulation.hydro]
use = true
outputfile = "hydro.out"
effect = true

# Use of hydroeffect is required at the moment since we cannot import data.
[simulation.hydroeffect]

[simulation.hydroeffect.temp]
base = 8e09
effect = "radial"

[simulation.hydroeffect.density]
base = 1e08
effect = "radial"

[simulation.thermo]
use = false
networkfile = "data/network-alpha.aad"
ratefile = "data/ratelibrary-alpha.aad"

[simulation.neutrino]
use = false
opacityfile = "data/FENNData40M186.h5"

# For the python code only.
[visualization]
save = false
saveas = "out.mp4"
